import dotenv from 'dotenv';

dotenv.config();
const {
  NODE_ENV,
  PORT,
  DEV_DATABASE_URL,
  TEST_DATABASE_URL,
  PROD_DATABASE_URL,
  SECRET_KEY,
  API_URL,
  SALT_ROUNDS,
  SENDGRID_API_KEY,
  EMAIL_SENDER,
  URL,
  VERIFY_URL,
  CLOUDINARY_CLOUD_NAME,
  CLOUDINARY_API_KEY,
  CLOUDINARY_API_SECRET
} = process.env;

const EXPIRATION_DURATION = 172800;

export {
  NODE_ENV,
  PORT,
  DEV_DATABASE_URL,
  TEST_DATABASE_URL,
  PROD_DATABASE_URL,
  SECRET_KEY,
  API_URL,
  SALT_ROUNDS,
  EXPIRATION_DURATION,
  SENDGRID_API_KEY,
  EMAIL_SENDER,
  URL,
  VERIFY_URL,
  CLOUDINARY_CLOUD_NAME,
  CLOUDINARY_API_KEY,
  CLOUDINARY_API_SECRET
};
